services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    ports:
      - "${SERVER_PORT}:8001"
    networks:
      - app-network

  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
