FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm@9.12.2
RUN npm i -g tsx

# Copy only what's needed for install and generation
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install
RUN pnpm prisma generate

# Now copy the full app code
COPY . .

EXPOSE 8001
CMD ["sh", "-c", "pnpm run prisma:migrate:prod && pnpm run dev"]

