FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm@9.12.2
RUN npm i -g tsx

# Copy package.json and prisma schema first
COPY package.json pnpm-lock.yaml ./
COPY prisma/schema.prisma ./prisma/

RUN pnpm install
RUN pnpm prisma generate

COPY . .

EXPOSE 8001

CMD ["pnpm", "dev"]
